name = "Nemo"
uuid = "2edaba10-b0f1-5616-af89-8c11ac63239a"
version = "0.27.4"

[deps]
AbstractAlgebra = "c3fe647b-3220-5bb0-a1ea-a7954cac585d"
Antic_jll = "e21ec000-9f72-519e-ba6d-10061e575a27"
Arb_jll = "d9960996-1013-53c9-9ba4-74a4155039c3"
Calcium_jll = "fcfa6d1b-d8ce-59d5-8c0a-c0d7f69e4f40"
FLINT_jll = "e134572f-a0d5-539d-bddf-3cad8db41a82"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomExtensions = "fb686558-2515-59ef-acaa-46db3789a887"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
AbstractAlgebra = "^0.22.3"
Antic_jll = "~0.200.500"
Arb_jll = "~200.2000.0"
Calcium_jll = "~0.400.100"
FLINT_jll = "^200.800.300"
RandomExtensions = "0.4.2"
julia = "1.6"
